### ISSUE TITLE
Setup API Gateway

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#64]

**Comment by rahulkrishnan221** [comment]
I am curious why you cloudformation or cdk are not being used?
Are you creating these resources manually?

**Comment by daltonfury42** [comment]
Hi @rahulkrishnan221 would love to know your thoughts on this... 

Since we are still in the hobby project / prototype phase, and I have no plans on monetising, I want to stay within free tier limit as much as possible. I have set up CICD via TravisCI+CodeDeploy, and code is just the jar running on a ec2 machine. 

The develop -> push -> deploy workflow is pretty smooth. 

For this setup, I thought that cloudformation would be an overkill, and hence did not bother to learn or set it up. What do you have in mind?

**Comment by rahulkrishnan221** [comment]
CDK/cloudformation makes life much easier once setup due to following reasons.
1. In case if you are migrating this project to some other aws account or it became big with lot of resources and you have Cloudformation/cdk in place  it will be 2 -3 line of command and all your resources will be created/deployed again easily.
2. I am seeing issues such as adding NLB/API gateway or setting cloudwatch logs/alarms those thing will become part of your stack, from that I am seeing a huge possibility that at some point your service will be eating lot of resources and at that case resource management will become a big issue.
3. Cloudformation/cdk is in free-tier, these services provide to you by aws out of box solution for easy creation and manitainence of resources.
4. SimplQ is pretty good idea and it is possible that many developer will contribute in future so in that case it will be difficult for them to replicate the stack in case if you don't have Cloudformation/cdk not in place.

**Comment by rahulkrishnan221** [comment]
Hi @daltonfury42 let me know if can contribute by introducing cdk ?

**Comment by daltonfury42** [comment]
Sure, I would like to connect with you whenever you are available. We can
discuss the design (current one is hacky) and you might come up with a
better one.

I am available anytime including now.

**Comment by rahulkrishnan221** [comment]
How could we connect could you provide your email or discord id or anything else?

**Comment by daltonfury42** [comment]
Lets connect on linkedin then I can send you a google meet link.

https://www.linkedin.com/in/navaneeth-kishore/

**Comment by daltonfury42** [comment]
@rahulkrishnan221 you can create more specific issues as we discussed. I'll close this one for now
